### ISSUE TITLE
Allow filter attrs in URL to be kebab-cased

### ISSUE THREAD

**Issue by ngscheurich** [ngscheurich/undermountain#5]
Basically `this-attr` in the request needs to become `this_attr` on the server.

**Comment by bienjensu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow filter attrs in URL to be kebab-cased](https://trello.com/c/0IRGU9WJ/81-allow-filter-attrs-in-url-to-be-kebab-cased)
